### ISSUE TITLE
Is it possible to include a custom mu-plugin from my repo?

### ISSUE THREAD

**Issue by jonlow** [colorful-tones/wpe-deploy-composer#1]
I would like to add a custom /mu-plugin to my git repo and have it included in the deploy. eg `/mu-plugins/my-test-mu-plugin`

I've added `/mu-plugins/my-test-mu-plugin` to `include.txt` but the plugin is never added to WP Engine.

I can confirm that this works for custom plugins in the `plugins` folder, just not the `mu-plugins` folder

**Comment by jonlow** [comment]
In my exclude.txt I had to add  `/mu-plugins/*` to match the path of my `/mu-plugins/my-test-mu-plugin` in include.txt.

The mu-plugin now syncs correcltly

**Comment by colorful-tones** [comment]
Glad you figured it out @jonlow 👍
